### PR TITLE
Update to iOS 7 (min) and 64bits architecture

### PR DESCRIPTION
**Pull request by PabloLerma**
Hi!

We've updated your Pod to support from iOS 7 and 64bits architecture.

We will be glad if you could accept our pull request.

Thanks!

### CODE REVIEW

**Comment by Antondomashnev** [comment]
Hi PabloLerma,

Thanks for that pull request.
I'm glad to do it.

**Comment by PabloLerma** [comment]
@Antondomashnev could you tag the release so the podspec point to the last version? thx!

**Comment by Antondomashnev** [comment]
@Pablo I've done it.
Thanks again for that pull request.

2015-01-22 11:20 GMT+03:00 Pablo <notifications@github.com>:

> @Antondomashnev <https://github.com/Antondomashnev> could you tag the
> release so the podspec point to the last version? thx!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antondomashnev/ADTickerLabel/pull/9#issuecomment-70985735>
> .
>



-- 
-------
Anton Domashnev || Look At Media, iPhone Developer
mob.: +7 926 683 1069
anton.domashnev@lookatme. <anton.domashnev@empatika.com>ru
anton.domashnev@gmail.com <anton.domashnev@empatika.com>
Skype: anton_domashnev

**Comment by PabloLerma** [comment]
Hi @Antondomashnev ! Could you update the podspec to Cocoapods Specs repo or give me permissons (I have everything prepared) :smile:

**Comment by Antondomashnev** [comment]
I've added you as a collaborator

**Comment by PabloLerma** [comment]
Thanks man!

**Comment by PabloLerma** [comment]
@Antondomashnev have you add me to cocoapods too? I am getting the "You are not allowed to push new versions for this pod." message. I am not sure since I have not a pod but I think you have to add me as a collaborator for cocoapods more than here in Github:

> Adding other people as contributors

> For libraries with multiple maintainers, the first person to push a version can add other maintainers with the command pod trunk add-owner for example to add kyle@cocoapods.org to my library ARAnalytics I would run:

> $ pod trunk add-owner ARAnalytics kyle@cocoapods.org

Correct me if I am wrong :P

**Comment by Antondomashnev** [comment]
@PabloLerma Unfortunately I can't add you to the cocoapods repo as owner. So seems I have to push your pull request by myself

**Pull request merged**
